pipeline {
  agent any
  tools {
        maven "Maven_Jenkins" 
   }

  stages {
      stage('Build Artifact') {
            steps {
              sh "mvn clean package -DskipTests=true"
              archive 'target/*.jar' 
            }  
       }
  }
}
